# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Satosa-Saml2Spid

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev python3-pip xmlsec1 procps libpcre3 libpcre3-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r example_sp/djangosaml2_sp/requirements.txt
        pip install spid-sp-test>=0.9.2
        pip install flake8
        pip install satosa_oidcop
    - name: Lint with flake8
      run: |
        ## stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics example
        ## exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --max-line-length 120 --count --exit-zero --statistics example
    - name: run djangosaml2 sp
      run: |
        cd example_sp/djangosaml2_sp/
        bash run.sh &
        sleep 5
    - name: run satosa-saml2spid
      run: |
        cd example
        mkdir -p metadata/idp
        mkdir -p metadata/sp
        export SATOSA_APP=`python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'`
        uwsgi --wsgi-file $SATOSA_APP/satosa/wsgi.py  --https 0.0.0.0:10000,./pki/cert.pem,./pki/privkey.pem --callable app -b 32768 &
        sleep 5
    - name: spid-sp-test
      run: |
        cd example
        spid_sp_test --idp-metadata > metadata/idp/spid-sp-test.xml
        spid_sp_test --metadata-url https://localhost:10000/spidSaml2/metadata --extra --debug ERROR -tr
